spring:
  application:
    name: rest-keycloak-admin

server:
  port: 8083

keycloak:
  realm: springboot-keycloak
  server-url: http://localhost:8180/
  client-id: rest-admin-client
  client-secret: hTkGXg4EZxlpxlQ8ZjFFWtcBzzvVjLbP
#  connection-timeout: 5000
#  socket-timeout: 5000
#  connection-request-timeout: 5000


#Eureka configurations
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    org:
      keycloak: DEBUG
      springframework:
        security: DEBUG
    com.sebadevbank.usersservice: DEBUG