services:
  accountsdb:
    container_name: sebadevbank-accountsdb
    ports:
      - 3300:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config
  transactionsdb:
    container_name: sebadevbank-transactionsdb
    ports:
      - 3301:3306
    environment:
      MYSQL_DATABASE: transactionsdb
    extends:
      file: common-config.yml
      service: microservice-db-config
  cardsdb:
    container_name: sebadevbank-cardsdb
    ports:
      - 3302:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config


networks:
  sebadevbank:
    driver: "bridge"