server:
  port: 8082
spring:
  application:
    name: transactions
  datasource:
    url: jdbc:mysql://localhost:3301/transactionsdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

#Eureka configurations
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


info:
  app:
    name: "Transactions Microservice"
    description: "Microservicio para gestionar transacciones"
    version: "1.0.0"
    author: "seba dev"
